//if you add an api or something else to the config, you must also add it to the interface in the env.d.ts file
posconfig = {
    api: "http://dev.revelapps.com:9096",
    API_URL: "http://dev.revelapps.com:9096/api/",
    ASSERT_URL: "http://dev.revelapps.com:9096",
    signalRUrl: "http://dev.revelapps.com:9095/signalr/hubs",
    releasealltables: "/api/v2/administration/layout/releasealltables",
    GOOGLE_MAP_API_KEY: "AIzaSyCKU9vp7iC4eHOGvFO2sWfyCHeQ21UgFLY",
    reservationURL:"https://wwc.resengo.com/",
    DEV_ENV_LOCAL: true,
    isNotReload:true,
    reloadTime:10000,
    defaultLang:"nl",
    whatsappApi: "https://api.whatsapp.com/message/UF3DYMABTETGH1?autoload=1&app_absent=0",
    bill: "http://tabletmenukaart.ddns.net:9096/api/v2/bill/table/36/sufix/A",
    backgroundImage: "http://dev.revelapps.com:9096/api/v2/administration/layout/backgrounds",
    backgroundNewImage: "http://dev.revelapps.com:9096/api/v2/administration/layout/backgrounds/new/",
    uploadBackground: "http://dev.revelapps.com:9096/api/v2/administration/layout/backgrounds/upload",
    printers: "/api/v2/administration/settings/printersettings/printers",
    generalSettingsPrinters: "/api/v2/administration/settings/printersettings/generalsettings",
    floorSettings: "/api/v2/administration/settings/printersettings/floorsettings",
    kassaSettings: "/api/v2/administration/settings/printersettings/kassaipsettings",
    kitchenSettings: "/api/v2/administration/settings/printersettings/kitchenscreens",
    printingGroups: "/api//v2/administration/settings/printersettings/groups",
    printingGroupsCustomSettings: "/api/v2/administration/settings/printersettings/customsettings",
    connectedPrinters: "/api/v2/administration/settings/printersettings/groupsonprinters",
    customLabels: "/api/v2/administration/settings/printersettings/customlabels",
    searchTables: "/api/v2/order/searchtables"
}